ReplicaNumber: 1

containers:
  containerPort: 8080
  image: 'quay.io/anastasia_klimov/hw_im1'
  tag: 'chart_v1'

service:
  servicePort: 8080

probes:
  readinessPath: '/health/readiness'
  readiness:  
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  livenessPath: '/health/liveliness' 
  liveness: 
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  
volume:
  mount:
    path: /tmp/html

test: Healthy

github:
  user: AnastasiaK24
  token: empty-pass
  url: <https://api.github.com/repos/AnastasiaK24/app-dev-lab/issues>